### ISSUE TITLE
Hello there,

### ISSUE THREAD

**Issue by Goofychex** [otmarlendl/base45#1]
@otmarlendl 

- How do you run the script?

I want to Encode

But when i run **sudo gcc base45encode**

It gives me an error:

/usr/bin/ld: base45encode: stdout: invalid version 2 (max 0)
/usr/bin/ld: base45encode: error adding symbols: bad value
collect2: error ld returned 1 exit status

**Comment by otmarlendl** [comment]
Either use make as written in the readme, or try

gcc -o base45encode base45encode.c

(untested)
